### ISSUE TITLE
vTiger 6.1.0 popup options load as whole page

### ISSUE THREAD

**Issue by stefan-dimitrov** [sardoj/VTModuleDesigner#44]
Hello,
I have updated the module designer plugin(the version from Sep. 9th), and I later updated Vtiger to version 6.1.0.
Now when ever I choose an option i module designer that makes a popup, for example to load an existing module, to create a new field. Instead of a popup a new page gets loaded with the contents of the popup. Moreover the submit/save buttons do not redirect back to the main moduleDesigner page and I cannot apply the data.

Thanks.

**Comment by Jagyto** [comment]
I have the same problem with the recently updated vTiger 6.1.0

**Comment by sardoj** [comment]
Hello,

I think there is an issue with Fancybox. We will try to fix it.

Thanks for feedbacks.

**Comment by playmono** [comment]
Hi,

I just notice since Im working with vt6.1, ModuleDesigner is not working well at all.

I will look onto this asap.

**Comment by Luke1982** [comment]
I have the same issue in vTiger 6.0. I tried importing and uploading module but the pop-up opens as a whole page and clicking the links does nothing. Other than that great module BTW.

**Comment by emz3emz** [comment]
i also  have the same issue , any updates ?

**Comment by sardoj** [comment]
I will try soon to use Bootstrap into ModuleDesigner. It should fix these
issues.

**Comment by alexanderjp** [comment]
Sardoj, YOU ARE THE BEST!!!!!!!!

**Comment by emz3emz** [comment]
is it solved ?

**Comment by sardoj** [comment]
Lol no, i said "i _will_ try" ;-)

**Comment by emz3emz** [comment]
:D:D @alexanderjp i thought its done because of your comment 
i hope you can fix this soon as this is very needed thing 

at the same time if this is not fixed what is the way to build modules manually as i am new to PHP but having the concepts of programming and Asp.net

**Comment by alexanderjp** [comment]
Sorry @emx3emz, I was just thrilled with the great module and the effort @sardoj has been putting into this.

**Comment by vjstyla** [comment]
@sardoj , 
I am facing the same problem, also I have created 2-3 new module in vTiger 6 but now I am even unable to install them to 6.1.....

Can you guide me what needs to be done to cure this Pop-up problem

**Comment by emz3emz** [comment]
any new updates ?

**Comment by singasong4u** [comment]
just install 6.0 on your own virtual machine, to edit the modules use modules designer, after the work,download the modules from 6.0  and install in your 6.1.

**Comment by emz3emz** [comment]
thank you @singasong4u 

I just did that (Y) but i am having issue when openining the module in 6.0 i always find below error

Permission to perform the operation is denied for name ?

**Comment by singasong4u** [comment]
here is Jonathan`s answer on youtube:

Jonathan Sardo1 month ago

Hello,
I don't know why but the bug is caused because a row is not created into the table "vtiger_ws_entity".
Simply duplicate a row and put the module's name into "name" column.﻿

ps. my opinion is :
If you patch the vtlib, use English version and edit the module with English codes, not your Mather language(if not EN), it will not happened.

**Comment by emz3emz** [comment]
i am sorry because i am new to vtiger and php , how can i add such row ? shall i use a specific tool for mysql ?

**Comment by singasong4u** [comment]
Add a row from phpmyadmin. Login the phpmyadmin for your site , find the table "vtiger_ws_entity", then...

**Comment by emz3emz** [comment]
many thanks @singasong4u (Y) it worked

**Comment by playmono** [comment]
Hi, i resolved this issue upgrading fancybox to the latest version. However so many thanks stop working.. Im totally unable to resolve this, we will need to wait to sardoj :(

**Comment by emz3emz** [comment]
i didn't get it @playmono :(
do you mean it is solved or still ?

**Comment by sardoj** [comment]
With Vtiger 6.1, /libraries/csrf-magic/csrf-magic.php (line 175) adds in all iframes:

<script type="text/javascript">if (top != self) {top.location.href = self.location.href;}</script>

I fixed this bug adding in all views:
$GLOBALS['csrf']['frame-breaker'] = false;

**Comment by vjstyla** [comment]
Hi Sardoj,

Ok, Got that and it worked !!!

Thanks

**Comment by singasong4u** [comment]
I found when create a new module in VT6.1  with custom fields calculate,  it didnot work, then I installed a new En version, it still happened.
Does anyone has same problem?

**Comment by emz3emz** [comment]
@sardoj 
i replaced this line number175  :-
if ($GLOBALS['csrf']['frame-breaker'] && !$is_partial) {

with this :-
if ($GLOBALS['csrf']['frame-breaker'] =false && !$is_partial) {

is there another thing ?

**Comment by vjstyla** [comment]
He Emz3,

I have replaced this line and it worked fine

Line no. 118

$GLOBALS['csrf']['frame-breaker'] = true;

Replace true to "False" and done

Vijay

**Comment by sardoj** [comment]
@emz3emz @vjstyla You have nothing to modify. 
Simply download the new version of Module Designer and install it through the Settings Panel.
https://github.com/sardoj/VTModuleDesigner/blob/master/ModuleDesigner_2014-10-07.zip?raw=true

**Comment by playmono** [comment]
Hi was suspecting that CRSF protection would be, but I could never have solved the problem. Thanks @sardoj , the project Module Designer progresses :)

**Comment by playmono** [comment]
Anyway, for all this using this module, I think we should warning on this:

```
 /**
  * Set this to false if your site must work inside of frame/iframe elements,
  * but do so at your own risk: this configuration protects you against CSS
  * overlay attacks that defeat tokens.
  */
```

**Comment by Luke1982** [comment]
Thanks, I saw people above responding about vTiger 6.1, but I had the same problem for 6.0. The update solved it and now I can go around and play with this. I love this module!

**Comment by Luke1982** [comment]
One question: I created a block for an existing module, but accidentally clicked twice. When I try to drag the redundant block I get "you cannot remove a non-editable field'. Of course I can restart the procedure and do it right this time, but how can I overcome this?

**Comment by playmono** [comment]
fixed with pull from today

**Comment by bibingk** [comment]
How i fixed the  bug - vTiger 6.1.0 popup options load as whole page -  is  
go to the file -> layouts/vlayout/modules/Settings/ModuleDesigner/GetModulesPopup.tpl

Here i removed the html header part and copied the header content to the body .
It works for me ... 

PS : 100 thanks for Sarjod for making such an awasome stuff

**Comment by sardoj** [comment]
Hi bibingk!

Thanks for your help.
You can download the last version of the zip package and update Module Designer via the Settings Panel.
Everything work fine!

https://github.com/sardoj/VTModuleDesigner/blob/master/ModuleDesigner_2014-10-10.zip?raw=true

**Comment by kongoll** [comment]
@sardoj 

hi, can u share ModuleDesigner_2014-10-10.zip? i try to download but that file already disappear. i try install VTModuleDesigner6.1 and it display error  manifest.xml.

thanks
